# Generated by Django 3.2.8 on 2021-10-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_laptop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
